#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"


#a
cookbook "apparmor"

#b

#c

cookbook "chef-client"

#d

cookbook "dovecot"

#e

#f

#g


#h
cookbook "htop"

#i
cookbook "imagemagick"

#j


#k

#l

#m

#n

cookbook "nginx"

#o

cookbook "openssl"

#p

cookbook "php"
cookbook "php5-fpm"
cookbook "postfix"
cookbook "phpmd"
cookbook "phpcpd"
cookbook "phing"

#q

#r

#s


#t

#u


#v

#cookbook "vim"

#w

#x

cookbook "xdebug"

#y

#z

