name             'phpapp'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures phpapp'
long_description 'Installs/Configures phpapp'
version          '0.1.0'
